#/!bin/sh

convert(){
    cd $1
    gzip -9kf $2
    xxd -i $2.gz
    rm -f $2.gz
    cd ..
}

echo "/*Generated by convertHtmlFile.sh script*/" > camera_index.h

echo "#include \"config.h\"\n\n" >> camera_index.h
convert html index_ov2640.html >>camera_index.h
convert html index_ov3660.html >>camera_index.h

